apiVersion: v1
kind: Pod 
metadata:
  name: multi-pod 
spec:
  containers: 
    - name: sample 
      image: nginx 

    - name: demo  
      image: centos:7 
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']