apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  cli_lives: "4"
  

--- 
apiVersion: v1
kind: Pod 
metadata:
  name: config-pod 
spec:
  containers: 
    - name: centos  
      image: centos:7 
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600'] 
      env:  
        - name: URL
          value: google.com
        - name: DOMAIN 
          value: CloudNative 
        - name: ENV 
          value: sandbox 
        - name: APP
          value: au-app 