apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["sleep", "300"]
    envFrom: 
      


--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  URL: www.google.com 
  ENV: dev 
  TRAINING: devops 
  CLOUD: aws