apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: centos
    image: alpine 
    command: ["sleep", "300"]
    envFrom: 
      - configMapRef: 
          name: demo-configmap


--- 
apiVersion: v1
kind: Secret
metadata:
  name: demo-configmap
data:
  URL: www.google.com 
  ENV: dev 
  TRAINING: devops 
  CLOUD: aws

USERNAME: YWRtaW4K 
PASSWORD: cGFzc3dvcmQK