apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  cli_lives: "4"
  gadgets_price: "100"

--- 

apiVersion: v1
kind: Secret 
metadata:
  name: secret-demo
data:
  DBPASSWORD: ZGJwYXNzMjAyMgo=

--- 
apiVersion: v1
kind: Pod 
metadata:
  name: config-map-pod 
spec:
  containers: 
    - name: centos  
      image: centos:7 
      command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600'] 
      envFrom:
        - configMapRef: 
            name: game-demo   
        - secretRef: 
            name: secret-demo   
