apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:              # Labels for replicaSet
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:            # Labels for the pods
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3