apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # image: nginx:1.14.2 
        image: nginx:1.22
        ports:
        - containerPort: 80

# --- 
# # Creates a service of type ClusterIP : If you don't mention the type ClusterIP will be considered as a default service.
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-deployment-svc
# spec:
#   selector:
#     app: nginx
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80 

--- 

apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80